### ISSUE TITLE
[vite] The requested module '@meursyphus/flitter' does not provide an export named 'Colors'

### ISSUE THREAD

**Issue by juppdes** [meursyphus/flitter#71]
I just follow the steps in documentation for create a svelte project.

[vite] The requested module '@meursyphus/flitter' does not provide an export named 'Colors'

**Comment by Moon-DaeSeung** [comment]
I apologize for the confusion in the documentation. There was a slight error. Actually, you don't need to import a Colors export. When specifying colors, you can simply use string values.

```typescript
Container({
 color: 'red' // or you can specify rgba like css
 })
 ```
 
However, I have some good news! This issue prompted us to actually add a Colors export. We've just updated and released version 2.0.1, so if you update to the latest version via npm or yarn, you'll be able to use the Colors export.
After updating, you can use it like this:
 
 ```typescript
Container({
 color: Colors.red[900]  
 })
 ```
